### ISSUE TITLE
Tool

### ISSUE THREAD

**Issue by REAS** [jeffThompson/DarkProcessingTheme_3.0#1]
This could be a nice Tool as well: https://github.com/processing/processing/wiki/Tool-Overview

**Comment by jeffThompson** [comment]
A good suggestion, which I've thought about before. I'm afraid figuring out the API is too much work for me at the moment. Would you consider a "dark theme" option in the P5 Preferences pane? A quick switch for those not wanting to roll their own theme?

**Comment by REAS** [comment]
We feel good about this functionality as a Tool -- we want the PDE to cover the bare essentials with features added through Tools. Hopefully someone else can make a Tool and you can contribute your color scheme to it.

**Comment by jeffThompson** [comment]
Makes perfect sense. Let's see if I can fit some time in for this!
