### ISSUE TITLE
DarkProcessingTheme 4.0?

### ISSUE THREAD

**Issue by jeremydouglass** [jeffThompson/DarkProcessingTheme_3.0#10]
Hi Jeff,

Your DarkProcessingTheme series has been popular for a long time now. With Proceesing 4.0 beta just released, dark-theming is underway yet again on the forums: https://discourse.processing.org/t/processing-4-change-editor-window-colour/31717/4

Would you consider releasing a 4.0 of your DarkProcessingTheme? Theming is almost the same, but a bit simplified:

https://github.com/processing/processing4/wiki/Themes

**Comment by jeffThompson** [comment]
Thanks for the kind words! I actually had been meaning to put this repo in archive mode, like the Dark Arduino theme I also created. Super psyched for the new version of Processing but I've moved mostly to p5.js and don't have the time to maintain the theme. Happy for anyone who wants to to fork this, though!

Closing this with thanks!
