### ISSUE TITLE
Processing app not opening on windows machine after lib folder was replaced.

### ISSUE THREAD

**Issue by MichaelHelmers** [jeffThompson/DarkProcessingTheme_3.0#2]
Hello,
I believe the problem is that Processing now puts some executable jar files in the lib folder; so when I copied the lib folder over the Processing app would not open anymore.

To solve this I instead copied all of the items contained in the DarkProcessingTheme lib folder and replaced any that were already in the Processing lib folder with yours.  That way all the executable files stayed and the app was able to open.

**Comment by jeffThompson** [comment]
Thanks, instructions are now fixed!
