### ISSUE TITLE
Dark theme issue with 3.3

### ISSUE THREAD

**Issue by rpapson** [jeffThompson/DarkProcessingTheme_3.0#3]
I've used your theme ... which I like very much. Recently updated a different computer and downloaded the most recent version of Processing .... 3.3. This breaks your theme :(

![image](https://cloud.githubusercontent.com/assets/20669410/23680262/6e226674-033f-11e7-81d9-a572a02db289.png)

**Comment by jeffThompson** [comment]
@rpapson – finally getting around to this. For me, the issue was a (new) folder in `lib` with fonts in it. Can you re-install the theme and try for me (looks like you're on Windows, right)?

**Comment by totovr** [comment]
is this bug already fixed?

**Comment by jeffThompson** [comment]
@totovr – if you're on Windows, can you try installing and see?

**Comment by totovr** [comment]
@jeffThompson I’m in OS :(

**Comment by jeffThompson** [comment]
@totovr – I assume you mean Mac OS? Are you getting the same issue as the one in the screenshot? If not, can you please start a new issue?

**Comment by totovr** [comment]
I didn’t check it yet, but tomorrow I will prove it tomorrow

**Comment by jeffThompson** [comment]
Since this is now 2.5 years old, I'm going to close this – please open a new issue if you're still having problems!
