### ISSUE TITLE
Instructing to replace preferences.txt may break things

### ISSUE THREAD

**Issue by hamoid** [jeffThompson/DarkProcessingTheme_3.0#4]
The `preferences.txt` file contains the path to your sketch folder, among other important settings.

It would be nice to know which parts of `preferences.txt` should be updated, without throwing away your own preferences.

Or at least, the instructions should include which rows you should update after replacing the file.

**Comment by hamoid** [comment]
Maybe the only lines that should be copied from your preferences.txt file are those containing a `#` sign?

**Comment by jeffThompson** [comment]
It shouldn't break anything if you just replace it with the original. The sketchbook path will be wrong, but you'll probably be prompted to replace it when it can't be found. Was there something that got changed that you didn't want?

(Lines starting with `#` are colors, but there's lots of other things in there you might want to change too.)

**Comment by hamoid** [comment]
Hi! In my case, I use a different font, different font size, different console font size, I have a customized `launcher`, `run.display` has a different value, `editor.laf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel` is only present in mine (maybe differences between linux, mac and windows?). 

Basically, if the user has customized anything in the preferences.txt file, it would be lost, so I think it would be nice to know which changes you suggest making instead of replacing the whole thing :)

**Comment by jeffThompson** [comment]
Gotcha. I think as of P5 version 3.3, you don't need to install the new preferences file at all. Can you try it and see if your changes stay but the editor is not using the dark theme?

**Comment by jeffThompson** [comment]
This is now 2.5 years old and you def don't need to replace the `preferences.txt` file, so I'm going to close this.
